sudo: false
language: rust

cache:
  cargo: true
  directories:
    - $HOME/gcc-arm-none-eabi-6_2-2016q4

os:
  - linux
  - osx

# If you change this, you must also change README and Common.mk
rust:
  - nightly-2017-01-25

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./.travis-install-gcc; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH="$PATH:$HOME/gcc-arm-none-eabi-6_2-2016q4/bin"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap ARMmbed/homebrew-formulae; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install arm-none-eabi-gcc; fi

before_script: (cargo install rustfmt || true)

script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - tools/run_cargo_fmt.sh diff
  - make allboards
  - pushd userland/examples && ./build_all.sh

